
## Universidad Nacional de Colombia

Sistemas de Transporte de Energía Eléctrica

J.S. Torregrosa-Palmett - C.C 1193036531

##### *Abstract— esta solución ofrecerá una visión integral de Formulación y Taller para el Cálculo de Campos Electromagnéticos en Líneas Aéreas de Alta Tensión explorando diferentes enfoques y consideraciones para obtener un entendimiento sólido de las características eléctricas de la línea y su impacto en la operación del sistema eléctrico.*

##  INTRODUCCIÓN

La sección de soluciones del taller ofrece un desglose detallado de los métodos empleados para abordar el análisis de campos electromagnéticos en líneas de transmisión. Desde el cálculo del campo eléctrico en conductores hasta la evaluación del campo magnético en condiciones específicas, se exploran diversas estrategias para obtener resultados precisos y relevantes.

Este taller se enfoca en el cálculo de campos electromagnéticos en líneas de 230 kV, presentando una serie de pasos que incluyen el cálculo del campo eléctrico superficial en los conductores, la determinación del perfil del campo eléctrico a un metro del suelo y el análisis del campo magnético en diferentes escenarios de energización trifásica y corriente de línea.

La solución propuesta para el cálculo de campos electromagnéticos en líneas de 230 kV abarca desde el análisis del campo eléctrico en la superficie de los conductores hasta la evaluación del campo magnético a diferentes alturas del suelo. Se detalla el cálculo del campo eléctrico superficial, el perfil del campo eléctrico a un metro del suelo y el campo magnético para condiciones específicas de energización trifásica y corriente de línea de 1000 A.

Además, se aborda el perfil del campo eléctrico para líneas compactas, proporcionando una solución específica para este tipo de configuración. Se destaca la importancia de estas soluciones en la evaluación de la eficiencia y calidad de la transmisión, especialmente en situaciones de carga y falla.

La metodología analítica empleada en este taller se basa en ecuaciones y referencias específicas, como el "Electrical Transmission and Distribution Reference Book". Se enfatiza la relevancia de estos cálculos en la comprensión de la regulación de voltaje en diversas condiciones, incluyendo la sensibilidad ante la longitud de la línea y la influencia de la compensación con reactores de línea al 50%.

## DESARROLLO

* *A.  Taller Cálculo de Campos Electromagnéticos en Líneas de 230 kV   -  Calcular campo eléctrico superficial en los conductores - Calcular perfil de campo eléctrico a un metro del suelo - Calcular perfil de campo magnético*

In [ ]:
import math
import numpy as np

H_min = 6.5
H_prom = 20
R_cond_fase = 1.5989*10**-2
print(f'R de conductor a fase:', R_cond_fase)
print()

R_guarda = 0.489e-2
V_nom = 230e3
epsilon_0 = 8.8541878176


def pitagoras(a, b):
    return np.sqrt(a**2 + b**2)


Distancias_a_cond = np.array([[0, 4.7*2, pitagoras(9.4, 6)],
                              [4.7*2, 0, 6],
                              [pitagoras(9.4, 6), 6, 0]])
print(f'Distancia a conductor:', Distancias_a_cond)
print()

Distancias_a_img = np.array([[2*H_prom, pitagoras(2*H_prom, 4.7*2), pitagoras(2*H_prom+6, 4.7*2)],
                             [pitagoras(2*H_prom, 4.7*2), 2*H_prom, 2*H_prom+6],
                             [pitagoras(2*H_prom+6, 4.7*2), 2*H_prom+6, 2*H_prom+12]])
print(f'Distancias a imagenes: ', Distancias_a_img)
print()

lambda_abc = np.zeros((3, 3))

for i in range(3):
    for j in range(3):
        if i == j:
            lambda_abc[i, j] = np.log(Distancias_a_img[i, j] / R_cond_fase)
        else:
            lambda_abc[i, j] = np.log(Distancias_a_img[i, j] / Distancias_a_cond[i, j])

print(f'Lambda :' ,lambda_abc)
print()

from numpy.linalg import inv
lambda_abc_inv = inv(lambda_abc)
print("Inversa de lambda:", lambda_abc_inv)
print()

V_vector = [[230 / math.sqrt(3)],
            [230 / math.sqrt(3) * (math.cos(math.radians(-120)) + 1j * math.sin(math.radians(-120)))],
            [230 / math.sqrt(3) * (math.cos(math.radians(120)) + 1j * math.sin(math.radians(120)))]]
print("V_vector:", V_vector)
print()

Q = lambda_abc_inv*V_vector
print("Q:", Q)
print()
Mag_Q = abs(Q)
print("Mag_Q:", Mag_Q)
print()

def E_x_func(Q, xi, yi, x, y):
    return Q * ((x - xi) / ((x - xi)**2 + (y - yi)**2) - (x - xi) / ((x - xi)**2 + (y + yi)**2))

def E_y_func(Q, xi, yi, x, y):
    return Q * ((y - yi) / ((x - xi)**2 + (y - yi)**2) - (y + yi) / ((x - xi)**2 + (y + yi)**2))

xo = np.array([-4.7, 4.7, 4.7])
yo = np.array([H_prom, H_prom, H_prom + 6])
R = np.array([R_cond_fase, R_cond_fase, R_cond_fase])
print("R:", R)
print()

import numpy as np
import pandas as pd

def E_x_func(Q, xi, yi, x, y):
    return Q * ((x - xi) / ((x - xi)**2 + (y - yi)**2) - (x - xi) / ((x - xi)**2 + (y + yi)**2))

def E_y_func(Q, xi, yi, x, y):
    return Q * ((y - yi) / ((x - xi)**2 + (y - yi)**2) - (y + yi) / ((x - xi)**2 + (y + yi)**2))

xo = np.array([-4.7, 4.7, 4.7])
yo = np.array([H_prom, H_prom, H_prom + 6])
R = np.array([R_cond_fase, R_cond_fase, R_cond_fase])

Ex = E_x_func(Q, xo, yo, xo + R, yo) / 100
Ey = E_y_func(Q, xo, yo, xo + R, yo) / 100
E = Ex + Ey
Angulos_rad = np.angle(E)
Angulos_grad = np.rad2deg(Angulos_rad)
E_rms = np.abs(E)

Resultados_1 = pd.DataFrame({
        'Q': [Q],  # Assuming Q is a scalar
        'Mag_Q': [Mag_Q],  # Assuming Mag_Q is a scalar
        'E_rms': [E_rms],
        'Angulos_rad': [Angulos_rad],
        'Angulos_grad': [Angulos_grad]
    })

print("Ex:", Ex)
print()

print(Ey)
print()
print(E)
print()
print("Angulos_rad:",Angulos_rad)
print()
print("Angulos_grad:",Angulos_grad)
print()
print("E_rms:",E_rms)
print()
print("Resultados_1:",  Resultados_1)
print()


R de conductor a fase: 0.015989

Distancia a conductor: [[ 0.          9.4        11.15168149]
 [ 9.4         0.          6.        ]
 [11.15168149  6.          0.        ]]

Distancias a imagenes:  [[40.         41.08965807 46.95061235]
 [41.08965807 40.         46.        ]
 [46.95061235 46.         52.        ]]

Lambda : [[7.82473375 1.47504677 1.43750596]
 [1.47504677 7.82473375 2.03688193]
 [1.43750596 2.03688193 8.08709801]]

Inversa de lambda: [[ 0.13513888 -0.02057078 -0.01884022]
 [-0.02057078  0.13989822 -0.03157938]
 [-0.01884022 -0.03157938  0.13495649]]

V_vector: [[132.79056191361394], [(-66.39528095680694-115.00000000000003j)], [(-66.39528095680694+115.00000000000003j)]]

Q: [[17.9451684  +0.j         -2.73160537 +0.j
  -2.50180334 +0.j        ]
 [ 1.36580268 +2.36563964j -9.28858168-16.0882954j
   2.09672179 +3.63162868j]
 [ 1.25090167 -2.16662525j  2.09672179 -3.63162868j
  -8.96047435+15.51999683j]]

Mag_Q: [[17.9451684   2.73160537  2.50180334]
 [ 2.73160537 18.5771

* *Calcular perfil de campo eléctrico a un metro del suelo*



In [ ]:
import numpy as np

H_new = 6.5
Distancias_a_cond = np.array([[0, 4.7 * 2, np.sqrt((4.7 * 2)**2 + 6**2)],
                              [4.7 * 2, 0, 6],
                              [np.sqrt((4.7 * 2)**2 + 6**2), 6, 0]])

Distancias_a_img = np.array([[2 * H_new, np.sqrt((2 * H_new)**2 + (4.7 * 2)**2), np.sqrt((2 * H_new + 6)**2 + (4.7 * 2)**2)],
                             [np.sqrt((2 * H_new)**2 + (4.7 * 2)**2), 2 * H_new, 2 * H_new + 6],
                             [np.sqrt((2 * H_new + 6)**2 + (4.7 * 2)**2), 2 * H_new + 6, 2 * H_new + 12]])

lambda_abc = np.zeros((3, 3))


for i in range(3):
    for j in range(3):
        if i == j:
            lambda_abc[i, j] = np.log(Distancias_a_img[i, j] / R_cond_fase)
            continue
        lambda_abc[i, j] = np.log(Distancias_a_img[i, j] / Distancias_a_cond[i, j])

lambda_abc_inv = np.linalg.inv(lambda_abc)

Q = np.dot(lambda_abc_inv, V_vector)
Mag_Q = np.abs(Q)

print(f'lambda_abc:' , lambda_abc)
print()
print(f'lambda_abc_inv:' , lambda_abc_inv)
print()
print(f'Q:' , Q)
print()
print(f'Mag_Q:' , Mag_Q)
print()

xo2 = np.array([-4.7, 4.7, 4.7])
yo2 = np.array([H_new, H_new, H_new + 6])
R2 = np.array([R_cond_fase, R_cond_fase, R_cond_fase])

Ex2 = E_x_func(Q, xo2, yo2, xo2 + R2, yo2) / 100
Ey2 = E_y_func(Q, xo2, yo2, xo2 + R2, yo2) / 100

E2 = Ex2 + Ey2
Angulos_rad2 = np.angle(E2)
Angulos_grad2 = np.rad2deg(Angulos_rad2)
E_rms2 = np.abs(E2)

import pandas as pd

Resultados_2 = pd.DataFrame({
    'Q': [Q],
    'Mag_Q': [Mag_Q],
    'E_rms2': [E_rms2],
    'Angulos_rad2': [Angulos_rad2],
    'Angulos_grad2': [Angulos_grad2]
})

print(Resultados_2)

lambda_abc: [[6.70080365 0.53452825 0.64232188]
 [0.53452825 6.70080365 1.15267951]
 [0.64232188 1.15267951 7.35473012]]

lambda_abc_inv: [[ 0.15115245 -0.01005789 -0.01162449]
 [-0.01005789  0.15404001 -0.02326372]
 [-0.01162449 -0.02326372  0.14062818]]

Q: [[ 21.51122664 -0.18015935j]
 [-10.01852126-20.3899281j ]
 [ -9.33606907+18.84756754j]]

Mag_Q: [[21.51198106]
 [22.71827318]
 [21.03314022]]

                                                   Q  \
0  [[(21.511226643198533-0.18015934744189122j)], ...   

                                               Mag_Q  \
0  [[21.511981059063928], [22.71827317685464], [2...   

                                              E_rms2  \
0  [[13.437669945459854, 13.437669945459854, 13.4...   

                                        Angulos_rad2  \
0  [[-0.008374935484256838, -0.008374935484256838...   

                                       Angulos_grad2  
0  [[-0.47984845694226913, -0.47984845694226913, ...  


# CONCLUSIONES

* El taller adopta un enfoque integral para el análisis de campos electromagnéticos en líneas de transmisión de 230 kV. Cubre diversos aspectos, incluyendo el cálculo del campo eléctrico en la superficie de los conductores, la determinación del perfil del campo eléctrico a un metro sobre el suelo y el análisis del campo magnético bajo diferentes escenarios de energización trifásica y corriente de línea.
* La metodología empleada en el taller se basa en ecuaciones y referencias específicas, enfatizando la importancia de estos cálculos en la comprensión de la regulación de voltaje en diversas condiciones. El uso de métodos analíticos y referencias, como el "Electrical Transmission and Distribution Reference Book," resalta la aproximación rigurosa para garantizar precisión y relevancia en el análisis.
* El proyecto aborda consideraciones prácticas al proporcionar soluciones para la evaluación de la eficiencia y calidad de la transmisión, especialmente durante condiciones de carga y falla. Se profundiza en el análisis del perfil del campo eléctrico para configuraciones de líneas compactas, reconociendo la importancia de estas soluciones en escenarios del mundo real. Además, se destaca la consideración de factores como la longitud de la línea y la compensación con reactores de línea al 50% como parte de la comprensión más amplia de los sistemas de transmisión de energía.

##  REFERENCIAS

* [1]	L. Cardona. (2023, Ago). Taller para el Cálculo de Campos Electromagnéticos en Líneas Aéreas de Alta Tensión.

* [2]	OpenAI. "Respuesta proporcionada por ChatGPT." Mensaje de chat generado por ChatGPT. Available on: https://chat.openai.com
